### ISSUE TITLE
Require for the RD points used in TABLE 4

### ISSUE THREAD

**Issue by ZhangYuef** [huzi96/Coarse2Fine-PyTorch#2]
Thanks for sharing the work!

I am trying to reproduce the results in TABLE 4 of TPAMI 2021 paper. Specifically, I use the open-sourced RD points from [tensorflow/compression](https://github.com/tensorflow/compression) but I get the different BD-Rate results from TABLE 4. Parts of my reproduce:
| Methods             | Kodak   | Kodak-TPAMI 2021 |
| ------------------- | ------- | ---------------- |
| ICLR2018_factorized | 32.76%  | 32.45%           |
| ICLR2018_hyperprior | 6.53%   | 3.43%            |
| ICLR19              | -3.43%  | -4.94%           |
| BPG                 | 0       | 0                |
| JPEG                | 111.24% | 115.05%          |

The second column is my reproduce and the third one is from the paper. I follow the instruction in the paper to use bpp range [0.4, 1.15] for Kodak. 

Does the jitter < 5% in RD-Rate can be neglected since those RD curves are got by mathematically fitting? Also, I think it would be greatly appreciated that you could open-sourcing the RD points you used for those methods.

**Comment by huzi96** [comment]
The jitter may be due to the difference in the used interpolation method.

Here are the points: [bpp, PSNR (dB)]
ICLR2018 factorized:
[[ 0.12004768, 26.81590579],
 [ 0.19721815, 28.30260532],
 [ 0.31842126, 29.99836244],
 [ 0.49367947, 31.72285964],
 [ 0.73317295, 33.6688382 ],
 [ 1.04842122, 35.77904641],
 [ 1.46034749, 37.99930683],
 [ 1.96733093, 40.0629516 ]]

ICLR2018_hyperprior:
[[ 0.12748549, 27.24206466],
 [ 0.20631663, 29.06472367],
 [ 0.3211814 , 30.89077978],
 [ 0.48136393, 32.73602189],
 [ 0.68496789, 34.63703971],
 [ 0.96489122, 36.86098719],
 [ 1.31052992, 38.83483582],
 [ 1.73873901, 40.82808222]]

ICLR19:
[[ 0.1005444 , 27.64089224],
 [ 0.14531793, 28.8015183 ],
 [ 0.20252567, 29.89431261],
 [ 0.29850176, 31.19881032],
 [ 0.43401506, 32.85073809],
 [ 0.69004907, 35.17374293],
 [ 0.99436951, 37.31821059],
 [ 1.27113512, 38.9376673 ],
 [ 1.59261661, 40.3777134 ]]

BPG:
[[ 1.92971208, 41.47887286],
 [ 1.5989134 , 40.21253023],
 [ 1.31941054, 38.90195768],
 [ 1.0802002 , 37.57484552],
 [ 0.86662716, 36.22240718],
 [ 0.68469662, 34.85747379],
 [ 0.53313107, 33.53685383],
 [ 0.40522512, 32.22686496],
 [ 0.30310228, 30.97433846],
 [ 0.22347599, 29.80391885],
 [ 0.16102346, 28.68154931]]

JPEG:
[[ 0.25520409, 26.67051871],
 [ 0.44836595, 29.13867092],
 [ 0.60891469, 30.49278333],
 [ 0.74152035, 31.41972802],
 [ 0.86686452, 32.17442926],
 [ 1.0021091 , 32.90818387],
 [ 1.20890469, 33.915194  ],
 [ 1.5424313 , 35.36971615],
 [ 2.7398368 , 39.16140764]]

**Comment by ZhangYuef** [comment]
> The jitter may be due to the difference in the used interpolation method.
> 
> Here are the points: [bpp, PSNR (dB)]
> ICLR2018 factorized:
> [[ 0.12004768, 26.81590579],
> [ 0.19721815, 28.30260532],
> [ 0.31842126, 29.99836244],
> [ 0.49367947, 31.72285964],
> [ 0.73317295, 33.6688382 ],
> [ 1.04842122, 35.77904641],
> [ 1.46034749, 37.99930683],
> [ 1.96733093, 40.0629516 ]]
> 
> ICLR2018_hyperprior:
> [[ 0.12748549, 27.24206466],
> [ 0.20631663, 29.06472367],
> [ 0.3211814 , 30.89077978],
> [ 0.48136393, 32.73602189],
> [ 0.68496789, 34.63703971],
> [ 0.96489122, 36.86098719],
> [ 1.31052992, 38.83483582],
> [ 1.73873901, 40.82808222]]
> 
> ICLR19:
> [[ 0.1005444 , 27.64089224],
> [ 0.14531793, 28.8015183 ],
> [ 0.20252567, 29.89431261],
> [ 0.29850176, 31.19881032],
> [ 0.43401506, 32.85073809],
> [ 0.69004907, 35.17374293],
> [ 0.99436951, 37.31821059],
> [ 1.27113512, 38.9376673 ],
> [ 1.59261661, 40.3777134 ]]
> 
> BPG:
> [[ 1.92971208, 41.47887286],
> [ 1.5989134 , 40.21253023],
> [ 1.31941054, 38.90195768],
> [ 1.0802002 , 37.57484552],
> [ 0.86662716, 36.22240718],
> [ 0.68469662, 34.85747379],
> [ 0.53313107, 33.53685383],
> [ 0.40522512, 32.22686496],
> [ 0.30310228, 30.97433846],
> [ 0.22347599, 29.80391885],
> [ 0.16102346, 28.68154931]]
> 
> JPEG:
> [[ 0.25520409, 26.67051871],
> [ 0.44836595, 29.13867092],
> [ 0.60891469, 30.49278333],
> [ 0.74152035, 31.41972802],
> [ 0.86686452, 32.17442926],
> [ 1.0021091 , 32.90818387],
> [ 1.20890469, 33.915194 ],
> [ 1.5424313 , 35.36971615],
> [ 2.7398368 , 39.16140764]]


Thanks for sharing!
